# Generated by Django 2.1.7 on 2019-03-21 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.PessoaJuridica')),
                ('setor_pai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_setores', to='administracao.Setor')),
            ],
        ),
        migrations.CreateModel(
            name='SetorTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='setor',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracao.SetorTipo'),
        ),
    ]
