# Generated by Django 2.2 on 2019-04-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeDeEnsino',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.PessoaJuridica')),
                ('tipo', models.IntegerField(choices=[(1, 'Instituto'), (2, 'Campus'), (3, 'Polo')])),
            ],
            options={
                'abstract': False,
            },
            bases=('base.pessoajuridica',),
        ),
    ]
