# Generated by Django 2.2 on 2019-04-10 16:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiretoriaEnsino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='unidadedeensino',
            managers=[
                ('por_tipo', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='unidadedeensino',
            name='pessoajuridica_ptr',
        ),
    ]
