# Generated by Django 2.2 on 2019-04-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_auto_20190410_1252'),
        ('base', '0004_unidadeorganizacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadedeensino',
            name='unidadeorganizacional_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.UnidadeOrganizacional'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidadedeensino',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Campus'), (2, 'Polo'), (3, 'Escola')]),
        ),
        migrations.AddField(
            model_name='diretoriaensino',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.PessoaFisica'),
        ),
    ]
