# Generated by Django 2.2 on 2019-04-09 17:36

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models
import sagii.commons.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoLimitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Deficiência'), (2, 'Transtorno')])),
                ('descricao', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoPessoalTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Documento Pessoal Tipo',
                'verbose_name_plural': 'Documentos Pessoais Tipos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome_razao_social', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Pessoa')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('estado_civil', models.IntegerField(blank=True, choices=[(1, 'Solteiro'), (2, 'Casado'), (3, 'Viúvo'), (4, 'Divorciado')], null=True)),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('natural_cidade', models.CharField(blank=True, max_length=120, null=True)),
                ('natural_uf', localflavor.br.models.BRStateField(blank=True, max_length=2, null=True)),
                ('nacionalidade', models.CharField(blank=True, choices=[('BR', 'Brasileiro'), ('EST', 'Estrangeiro')], default='BR', max_length=3, null=True)),
                ('falecido', models.BooleanField(default=False)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True)),
                ('condicoes_limitantes', models.ManyToManyField(to='base.CondicaoLimitante')),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
            },
            bases=('base.pessoa',),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Comercial'), (2, 'Residencial'), (3, 'Rural')])),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('uf', localflavor.br.models.BRStateField(max_length=2)),
                ('principal', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_endereco_related', related_query_name='base_enderecos', to='base.Pessoa')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Tel. Fixo'), (2, 'Tel. Celular')])),
                ('numero', models.CharField(max_length=120, validators=[sagii.commons.validators.PhoneRegexValidator()])),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_telefone_related', related_query_name='base_telefones', to='base.Pessoa')),
            ],
            options={
                'unique_together': {('numero', 'pessoa')},
            },
        ),
        migrations.CreateModel(
            name='RelacaoDependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau_parentesco', models.IntegerField(choices=[(1, 'Pai/Mãe'), (2, 'Avô/Avó'), (3, 'Tio/Tia'), (4, 'Outro')], null=True)),
                ('grau_parentesco_outro', models.CharField(blank=True, max_length=60, null=True)),
                ('dependente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='base.PessoaFisica')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='_deps', to='base.PessoaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Pessoa')),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, unique=True)),
                ('matriz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filiais', to='base.PessoaJuridica')),
            ],
            options={
                'verbose_name': 'Pessoa Jurídica',
                'verbose_name_plural': 'Pessoas Jurídicas',
            },
            bases=('base.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='dependentes',
            field=models.ManyToManyField(through='base.RelacaoDependencia', to='base.PessoaFisica'),
        ),
        migrations.CreateModel(
            name='DocumentoPessoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('valor', models.CharField(max_length=60)),
                ('observacoes', models.CharField(blank=True, max_length=140, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_documentopessoal_related', related_query_name='base_documentopessoals', to='base.Pessoa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.DocumentoPessoalTipo')),
            ],
            options={
                'verbose_name': 'Documento Pessoal',
                'verbose_name_plural': 'Documentos Pessoais',
                'unique_together': {('tipo', 'pessoa')},
            },
        ),
        migrations.CreateModel(
            name='ContatoSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Telegram', 'Telegram'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Website', 'Website'), ('Email', 'Email'), ('Skype', 'Skype'), ('Linkedin', 'Linkedin')], max_length=60)),
                ('valor', models.CharField(max_length=60)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_contatosocial_related', related_query_name='base_contatosocials', to='base.Pessoa')),
            ],
            options={
                'verbose_name': 'Contato Social',
                'verbose_name_plural': 'Contatos Sociais',
                'unique_together': {('pessoa', 'tipo')},
            },
        ),
    ]
