# Generated by Django 2.2 on 2019-04-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0002_auto_20190409_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='matriz',
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
