# Generated by Django 2.1.7 on 2019-04-02 03:56

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190321_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopessoal',
            name='observacoes',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='estado_civil',
            field=models.IntegerField(blank=True, choices=[(1, 'Solteiro'), (2, 'Casado'), (3, 'Viúvo'), (4, 'Divorciado')], null=True),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=localflavor.br.models.BRCNPJField(max_length=18, unique=True),
        ),
    ]
