# Generated by Django 2.2 on 2019-04-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0003_auto_20190409_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeOrganizacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sigla', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=140)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('pessoa_juridica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.PessoaJuridica')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
