# Generated by Django 2.2 on 2019-04-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190401_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatosocial',
            name='tipo',
            field=models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Telegram', 'Telegram'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Website', 'Website'), ('Email', 'Email'), ('Skype', 'Skype'), ('Linkedin', 'Linkedin')], max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='endereco',
            unique_together=set(),
        ),
    ]
